### ISSUE TITLE
Issue with get_columns(...)

### ISSUE THREAD

**Issue by ais-one** [lazymofo/datagrid#13]
The following query will have error

```
SELECT
    j.LogId,j.Id,GROUP_CONCAT(L.Code ORDER BY FIND_IN_SET(L.Id, j.Locations))
FROM
    job_log j
LEFT JOIN
    location L ON FIND_IN_SET(L.Id, j.Locations) != 0 
WHERE
    j.Id = 3
```

The **ORDER BY** onwards will be replaced in get_columns() function with blank, so the query is truncated, and there will be error.

from get_columns(...) ...

```
        // simplify query for faster execution
        $sql = rtrim($sql, "\r\n\t; ");                         // remove last semicolon
        $sql = preg_replace('/order\s+by\s+.+$/i', '', $sql);   // remove order
        $sql = preg_replace('/limit\s+[0-9,\s]+$/i', '', $sql); // remove limit
        $sql .= ' limit 0 ';                                    // add limit
```

Is it possible not to have the remove order?

**Comment by ais-one** [comment]
Found another place which needs to be changed. LIne 838 

```
            $sql = preg_replace('/order\s+by\s+.+$/i', '', $sql); // remove existing order
```

But I think commenting out is not the right thing to do. Thinking of a better solution to replacing order by

**Comment by ais-one** [comment]
Two possible solutions so far,
1. use case to identify whether to replace order by

```
 preg_replace('/order\s+by\s+.+$/i'

to

 preg_replace('/order\s+by\s+.+$/'
```
1. add a special marker in the grid_sql to find and replace...

e.g. Order*By

solution 2 may cause less existing code breakage...

**Comment by premax** [comment]
Found the same bug, because my query also contains a subquery with _order by_ clause. I think the cleanest solution is to tweak regexp to check if the ORDER BY we are going to remove (in function grid, line 841) is not defined within a subquery. 

For this I tweaked an regexp from:
`$sql = preg_replace('/order\s+by\s+.+$/i', '', $sql); // remove existing order`
to:
`$sql = preg_replace('/order\s+by\s+[^\)]+$/i', '', $sql); // remove existing order`

So now I check if there is no closing bracket after ORDER BY clause.

**Comment by lazymofo** [comment]
Dear Premax,

Thanks for catching this issue, I had thought I already addressed this
problem, but I was wrong. I've tweaked the code so it should remove the
last order by.

Your solution was a good suggestion, but it does not account for functions
in the order by clause. Example: "order by coalesce(field, '')"

Thanks for posting the issue!
-Ian

**Comment by premax** [comment]
Hello, after 3 years I've upgraded to the new LM library (v2020-02-17) and the bug is still there. I take your point that my solution is not perfect, but your current solution:

```
this->mb_preg_match_all('/order\s+by\s/im', $sql, $matches, PREG_OFFSET_CAPTURE);
if(count($matches) > 0){
$match = end($matches[0]);
$sql = mb_substr($sql, 0, $match[1]);
 }
```

is not perfect either. 

I have a select with ORDER clause in GROUP_CONCAT and your solution, which is looking for LAST ORDER BY is cutting the select on GROUP_CONCAT if there is no other ORDER BY clause (what happens in default, not sorted grid view).

This is my query, it will be cut off:

```
SELECT group_concat(distinct `l1`.`Description` order by `l1`.`Description` separator ",") AS `Readership` FROM `BookAll` `b` LEFT JOIN `List` `l1` ON FIND_IN_SET(`l1`.`id`,`b`.`list_id`) GROUP BY `b`.`Product_id`
```

Cheers.

**Comment by lazymofo** [comment]
Yeah, that bug is a known issue. I'd need a full query parsing library to
properly avoid that issue.
instead just add a 'order by' clause to your query as a work around.

that issue is kinda mentioned in the demo here:
https://github.com/lazymofo/datagrid/blob/master/demo.php#L106
